export const SET_MACHA_QUESTIONS = 'MACHA_QUESTIONS';

export const SET_PLAYERS = 'SET_PLAYERS';
export const ADD_PLAYER_POINT = 'ADD_PLAYER_POINT';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR';     